### ISSUE TITLE
About the Loss_graph_learning

### ISSUE THREAD

**Issue by fuchenye123** [ziyujia/GraphSleepNet#6]
Hello, I read the paper and found there is a Loss_graph_learning term as regularization, but I can't see that in the codes. Where is the Loss_graph_learning in the codes? looking forward to your answer.

**Comment by NingXJ1999** [comment]
We implemented the loss using `add_loss` in Graph Learn Layer. Please refer to lines 145-164 and 186-188 in the file `model/GraphSleepNet.py`.
